### ISSUE TITLE
👋 Hi, Could you please help me?

### ISSUE THREAD

**Issue by hslee2008** [BayBreezy/vuetify3-nuxt3-sass-customized#1]
Sorry to bother you and contact you this way.
I couldn't find the discussions tab.

So, I am having a bit of trouble with Vuetify SASS Variable customization.
I tried copying from this amazing repo you created, but I don't know what's wrong with my project.

This is my repo below:
https://github.com/HyunseungLee-Travis/littlechildwriter/tree/sass-vuetify

**Comment by BayBreezy** [comment]
Hey @HyunseungLee-Travis , 

I noticed that you are using tailwindcss & the daisy ui plugin. If you are going to mix tailwind with vuetify, you have to set a prefix in your `tailwind.config` file. See here for more details on prefix: [TailwiindCSS Prefix](https://tailwindcss.com/docs/configuration#prefix).

Also, in your `nuxt.config` file, you can remove the scss variables file. So remove this line https://github.com/HyunseungLee-Travis/littlechildwriter/blob/sass-vuetify/nuxt.config.ts#L84

Let me know if any of this helped :)

**Comment by hslee2008** [comment]
Okay. My mistake. I removed tailwind to use only Vuetify and removed the 84th line.

Also, I tried this:

```
@use 'vuetify/settings' with (
  $card-elevation: 0
);
```

But it didn't work. The card's elevation is still there.

**Comment by BayBreezy** [comment]
Oh ok. Can you share the repo again please.. That way I can clone it and see what is happening?

**Comment by hslee2008** [comment]
I deleted the branch. Sorry

[Repo main](https://github.com/HyunseungLee-Travis/littlechildwriter)

**Comment by BayBreezy** [comment]
Hey @HyunseungLee-Travis , I tried debugging this but could not find the issue. Sorry bud

**Comment by hslee2008** [comment]
It's okay. Thanks so much for trying. I will contact you again when it works.

**Comment by hslee2008** [comment]
@BayBreezy I just updated to Vuetify 3.1.3 and it worked! I am not sure what was wrong before, but it now works somehow.

**Comment by BayBreezy** [comment]
These things can be so funny sometimes. I am happy that it now works :)
