### ISSUE TITLE
i have some trouble with error [unhandledRejection] No known conditions for "./settings" specifier in "vuetify" package 

### ISSUE THREAD

**Issue by webzhou** [BayBreezy/vuetify3-nuxt3-sass-customized#2]
[unhandledRejection] No known conditions for "./settings" specifier in "vuetify" package

**Comment by BayBreezy** [comment]
hello @webzhou ,
I was not able to reproduce this.
I update some stuff just now. Can you check again to see if it works now? (It's working on my end)
