### ISSUE TITLE
Unexpected logs with nuxt 3.7

### ISSUE THREAD

**Issue by jd-solanki** [BayBreezy/vuetify3-nuxt3-sass-customized#3]
Hi 👋🏻 

After [this](https://github.com/vuetifyjs/vuetify-loader/issues/290#issuecomment-1696923578) comment. I tried your repo and found that your repo also gets logs like below when nuxt **3.7** is used:
<img width="704" alt="image" src="https://github.com/BayBreezy/vuetify3-nuxt3-sass-customized/assets/47495003/5cd3666d-13e5-436e-bdb3-cd9cb260fc65">

Do you have any idea what went wrong and how to make it work with nuxt 3.7?

**Comment by BayBreezy** [comment]
@jd-solanki This is no longer happening. 

I am sure you have moved on from this repo a long time ago but thanks anyways.
